Don't use Macports, use Brew instead. Plus start setting up for non-Mac environment.

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -3,19 +3,20 @@
 # TODO This doesn't work with proxy based access
 
 DOTFILES_DIRECTORY="${HOME}/.dotfiles"
+DOTFILES_BACKUPS="${DOTFILES_DIRECTORY}/backup"
 DOTFILES_TARBALL_PATH="https://github.com/seiryu9/dotfiles/tarball/master"
 DOTFILES_GIT_REMOTE="git@github.com:seiryu9/dotfiles.git"
 
 # If missing, download and extract the dotfiles repository
 if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
-    printf "$(tput setaf 7)Downloading dotfiles...\033[m\n"
-    mkdir ${DOTFILES_DIRECTORY}
-    # Get the tarball (TODO add -x for proxy support)
-    curl -fsSLo ${HOME}/dotfiles.tar.gz ${DOTFILES_TARBALL_PATH}
-    # Extract to the dotfiles directory
-    tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C ${DOTFILES_DIRECTORY}
-    # Remove the tarball
-    rm -rf ${HOME}/dotfiles.tar.gz
+	printf "$(tput setaf 7)Downloading dotfiles...\033[m\n"
+	mkdir ${DOTFILES_DIRECTORY}
+	# Get the tarball (TODO add -x for proxy support)
+	curl -fsSLo ${HOME}/dotfiles.tar.gz ${DOTFILES_TARBALL_PATH}
+	# Extract to the dotfiles directory
+	tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C ${DOTFILES_DIRECTORY}
+	# Remove the tarball
+	rm -rf ${HOME}/dotfiles.tar.gz
 fi
 
 cd ${DOTFILES_DIRECTORY}
@@ -23,132 +24,118 @@ cd ${DOTFILES_DIRECTORY}
 source ./lib/help
 source ./lib/list
 source ./lib/utils
-source ./lib/npm
-source ./lib/macports
-#source ./lib/brew
+source ./lib/brew
 
 # Help text
 if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-    run_help
-    exit
+	run_help
+	exit
 fi
 
 # List additional software to install
 if [[ "$1" == "-l" || "$1" == "--list" ]]; then
-    run_list
-    exit
+	run_list
+	exit
 fi
 
 # Test for known flags
 for opt in $@
 do
-    case $opt in
-        --no-packages) no_packages=true ;;
-        --no-sync) no_sync=true ;;
-        -*|--*) e_warning "Warning: invalid option $opt" ;;
-    esac
+	case $opt in
+		--no-packages) no_packages=true ;;
+		--no-sync) no_sync=true ;;
+		-*|--*) e_warning "Warning: invalid option $opt" ;;
+	esac
 done
 
-# Before relying on MacPorts, check that packages can be compiled
-if ! type_exists 'gcc'; then
-    e_error "The XCode Command Line Tools must be installed first."
-    printf "  Download them from: https://developer.apple.com/downloads\n"
-    printf "  Then run: bash ~/.dotfiles/bin/dotfiles\n"
-    exit 1
-fi
+if is_mac; then
+	# Before relying on Brew, check that packages can be compiled
+	if ! type_exists 'gcc'; then
+		e_error "The XCode Command Line Tools must be installed first."
+		if ! type_exists xcode-select; then
+			printf "  Install Apple's Xcode environment from the app store"
+			printf "  Then run: bash ~/.dotfiles/bin/dotfiles\n"
+		    exit 1
+		fi
+		e_header "Installing xcode command line tools"
+		xcode-select --install
+	fi
+	
+	if gcc --version > /dev/null 2>&1 ; then
+		e_header "Can't use gcc, trying sudo xcodebuild -license"
+		sudo xcodebuild -license
+	fi
 
-# Check for MacPorts
-if ! type_exists 'port'; then
-	e_error "MacPorts must be installed!"
-	exit 1
-fi
-
-# Check for Homebrew
-# if ! type_exists 'brew'; then
-#     e_header "Installing Homebrew..."
-#     ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
-# fi
-
-# Check for git
-if ! type_exists 'git'; then
-    e_header "Updating MacPorts..."
-    sudo port selfupdate
-    e_header "Installing Git..."
-	sudo port install git
+	# Check for Homebrew
+	if ! type_exists 'brew'; then
+		e_header "Installing Homebrew..."
+		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+	fi
 fi
 
 # Initialize the git repository if it's missing
 if ! is_git_repo; then
-    e_header "Initializing git repository..."
-    git init
-    git remote add origin ${DOTFILES_GIT_REMOTE}
-    git fetch origin master
-    # Reset the index and working tree to the fetched HEAD
-    # (submodules are cloned in the subsequent sync step)
-    git reset --hard FETCH_HEAD
-    # Remove any untracked files
-    git clean -fd
+	e_header "Initializing git repository..."
+	git init
+	git remote add origin ${DOTFILES_GIT_REMOTE}
+	git fetch origin master
+	# Reset the index and working tree to the fetched HEAD
+	# (submodules are cloned in the subsequent sync step)
+	git reset --hard FETCH_HEAD
+	# Remove any untracked files
+	git clean -fd
 fi
 
 # Conditionally sync with the remote repository
 if [[ $no_sync ]]; then
-    printf "Skipped dotfiles sync.\n"
+	printf "Skipped dotfiles sync.\n"
 else
-    e_header "Syncing dotfiles..."
-    # Pull down the latest changes
-    git pull --rebase origin master
-    # Update submodules
-    git submodule update --recursive --init --quiet
+	e_header "Syncing dotfiles..."
+	# Pull down the latest changes
+	git pull --rebase origin master
+	# Update submodules
+	git submodule update --recursive --init --quiet
 fi
 
 # Install and update packages
 if [[ $no_packages ]]; then
-    printf "Skipped package installations.\n"
+	printf "Skipped package installations.\n"
 else
-    e_header "Updating packages..."
-	# Install MacPorts
-	run_macports
-    # # Install Homebrew formulae
-    # run_brew
-    # Install Node packages
-    # run_npm
+	e_header "Updating packages..."
+	# Install Homebrew formulae
+	run_brew
 fi
 
 link() {
-    # Force create/replace the symlink.
-    ln -fs "${DOTFILES_DIRECTORY}/${1}" "${HOME}/${2}"
+	# Force create/replace the symlink.
+	if [ -f ${HOME}/${2} ]; then
+		cp -p ${HOME}/${2} ${DOTFILES_BACKUPS}/${2}
+	ln -fs "${DOTFILES_DIRECTORY}/${1}" "${HOME}/${2}"
 }
 
 mirrorfiles() {
-    ${DOTFILES_DIRECTORY}/bin/mirror-git
-	
-	# TODO Can Mercurial config also be done like git above?
-	
-    rsync -avz --quiet ${DOTFILES_DIRECTORY}/mercurial/hgrc  ${HOME}/.hgrc
-	e_warning "You must set username field in ~/.hgrc"
-	
+	${DOTFILES_DIRECTORY}/bin/mirror-git
 
-    # Force remove the vim directory if it's already there.
-    if [ -e "${HOME}/.vim" ]; then
-        rm -rf "${HOME}/.vim"
-    fi
+	# Force remove the vim directory if it's already there.
+	if [ -d "${HOME}/.vim" ]; then
+		rm -rf "${HOME}/.vim"
+	fi
 
-    # Create the necessary symbolic links between the `.dotfiles` and `HOME`
-    # directory. The `bash_profile` sources other files directly from the
-    # `.dotfiles` repository.
-    link "shell/bashrc"                ".bashrc"
-    link "shell/bash_profile"          ".bash_profile"
-    link "shell/curlrc"                ".curlrc"
-    link "shell/inputrc"               ".inputrc"
-    link "git/gitattributes"           ".gitattributes"
-    link "git/gitignore"               ".gitignore_global"
+	# Create the necessary symbolic links between the `.dotfiles` and `HOME`
+	# directory. The `bash_profile` sources other files directly from the
+	# `.dotfiles` repository.
+	link "shell/bashrc"				   ".bashrc"
+	link "shell/bash_profile"		   ".bash_profile"
+	link "shell/curlrc"				   ".curlrc"
+	link "shell/inputrc"			   ".inputrc"
+	link "git/gitattributes"		   ".gitattributes"
+	link "git/gitignore"			   ".gitignore_global"
 	link "mercurial/hgignore.defaults" ".hgignore.defaults"
-    link "vim"                         ".vim"
-    link "vim/gvimrc"                  ".gvimrc"
-    link "vim/vimrc"                   ".vimrc"
-	# TODO add subversion files
+	link "vim"						   ".vim"
+	link "vim/gvimrc"				   ".gvimrc"
+	link "vim/vimrc"				   ".vimrc"
 
-    e_success "Dotfiles update complete!"
+	e_success "Dotfiles update complete!"
 }
 
 # Ask before potentially overwriting files
@@ -156,11 +143,11 @@ e_header "Mirroring dotfiles..."
 seek_confirmation "Warning: This step may overwrite your existing dotfiles."
 
 if is_confirmed; then
-    mirrorfiles
-    source ${HOME}/.bash_profile
+	mirrorfiles
+	source ${HOME}/.bash_profile
 else
-    printf "Aborting...\n"
-    exit 1
+	printf "Aborting...\n"
+	exit 1
 fi
 
 # Ask before potentially overwriting OS X defaults
@@ -168,8 +155,8 @@ e_header "Setting OSX Defaults..."
 seek_confirmation "Warning: This step may modify your OS X system defaults."
 
 if is_confirmed; then
-    bash ./bin/osxdefaults
-    e_success "OS X settings updated! You may need to restart."
+	bash ./bin/osxdefaults
+	e_success "OS X settings updated! You may need to restart."
 else
-    printf "Skipped OS X settings update.\n"
+	printf "Skipped OS X settings update.\n"
 fi
