fix(config): pip is required to install
Test for availability of pip before allowing dotfiles to continue.

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -22,7 +22,12 @@ fi
 
 if ! type git > /dev/null ; then
 	echo "git is required to continue"
-	exit 2
+	exit 1
+fi
+
+if ! type pip > /dev/null ; then
+	echo "pip is required"
+	exit 1
 fi
 
 DOTFILES="${HOME}/.dotfiles"
